POST http://localhost:8080/carData
Content-Type: application/json

{
  "trip_id": "5d59e169-94a4-4bf7-8a8e-6a52a1d85f0f",
  "longitude": 45.123456,
  "latitude": 34.567890,
  "current_engine_rpm": 3000.0,
  "current_velocity": 60.0,
  "throttle_position": 75.0,
  "engine_run_time": "14:30:15",
  "time_stamp": "2023-11-08T13:45:00.000Z"
}

###

GET http://localhost:8080/carData/1
Accept: application/json

###

GET http://localhost:8080/carData
Accept: application/json

###

PUT http://localhost:8080/carData/1
Content-Type: application/json

{
  "id": 1,
  "trip_id": "5d59e169-94a4-4bf7-8a8e-6a52a1d85f0f",
  "longitude": 24.12,
  "latitude": 33.98,
  "current_engine_rpm": 3000.0,
  "current_velocity": 60.0,
  "throttle_position": 75.0,
  "engine_run_time": "14:30:15",
  "time_stamp": "2023-11-08T13:45:00.000Z"
}

###

DELETE http://localhost:8080/carData/1
Accept: application/json

###


